config/routes.rb
Benetech::Application.routes.draw do

  
  resources :submissions

  get 'submissions/:id/download_audio', to: 'submissions#download_audio'

  

  root 'welcome#index'

end

app/models/submission.rb
class Submission < ActiveRecord::Base
	validates :text, presence: true,
                    length: { minimum: 5 }
    validates :title, presence: true,
                    length: { minimum: 3 }


 def recording_to_file
     File.open(:title, "wb") do |f|
       f.write(:recording)
     end
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
http_basic_authenticate_with name: "benetech", password: "admin", only: :destroy


  def index
  	@submissions = Submission.all
  end

	def new
		@submission = Submission.new
	end

	def create
  		@submission = Submission.new(submission_params)
  		
  		if @submission.save and params[:commit] == 'Save Without Recording'
    		redirect_to @submission
    	elsif @submission.save and params[:commit] == 'Record Voiceover'
    		redirect_to edit_submission_path(@submission)
  		else
    		render 'new'
 		end
	end

	def show
		@submission = Submission.find(params[:id])
	end


  	def edit
		@submission = Submission.find(params[:id])
  	end

  	# This method saves recording as .wav file in audio_data folder and saves recording as binary in Rails database
  	def update
		puts "#{params}"
		id = params["id"].to_i
		@submission = Submission.find(id)
		audio = (params["audio_file"] == "" || params["audio_file"].nil?) ? params["audio"] : params["audio_file"]
		audio = audio.read

		data = ActionController::Parameters.new(audiouser: params["user"], recording: audio)
		if @submission.update(data.permit(:audiouser, :recording))
			
			##Saves files to audio_data folder
			filename = params["id"] + "_" + @submission.title.gsub(" ", "_") + "_" + params["user"].gsub(" ", "_")  # filename = id_title_user
			save_path = Rails.root.join("audio_data/#{filename}.wav")
			redirect_to edit_submission_path(@submission) if audio.nil? 	
		    # Open and write the file to file system.
			File.open(save_path, 'wb') do |f|
				f.write audio
			end
			##
			render :json => {
				:message => "Recording successfully saved!"
			}
		else
			render :json => {
				:message => "ERROR: recording failed"
			}
			redirect_to edit_submission_path(@submission)
		end
	end

	def download_audio
		@submission = Submission.find(params[:id])
    	send_file Rails.root.join("audio_data/#{@submission.id}_#{@submission.title.gsub(" ", "_")}_#{@submission.audiouser.gsub(" ", "_")}.wav"), :type=>"application/wav" 
  	end

	def destroy
	  @submission = Submission.find(params[:id])
	  @submission.destroy
	  user = @submission.audiouser.nil? ? "" : @submission.audiouser
	  path_to_file = Rails.root.join("audio_data/#{@submission.id}_#{@submission.title.gsub(" ", "_")}_#{user.gsub(" ", "_")}.wav")
	  puts "Deleting #{path_to_file}" if File.exist?(path_to_file)
	  File.delete(path_to_file) if File.exist?(path_to_file)
	  redirect_to submissions_path
	end
 
private
  def submission_params
    params.require(:submission).permit(:title, :text, :recording, :textuser, :audiouser)
  end





end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Benetech</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/submissions/edit.html.erb
<%= javascript_include_tag 'recorderWorker.js.erb' %>
<%= javascript_include_tag 'recorder.js.erb' %>
<div id="arrow">
  <%= link_to "<- Cancel", submissions_path%>
</div>
<p id="identification">
  <%= @submission.id %>
</p>
<div id="title_container">
  <h1> Add Recording </h1>
</div>

<head>
  <%= yield :head %>
</head>

<script>
  var onFail = function(e) {
	console.log('Rejected!', e);
  };

  var userRecording = null;

  var onSuccess = function(s) {
	var context = new webkitAudioContext();
	var mediaStreamSource = context.createMediaStreamSource(s);
	recorder = new Recorder(mediaStreamSource);
	recorder.record();

	// audio loopback
	// mediaStreamSource.connect(context.destination);
  }

  window.URL = window.URL || window.webkitURL;
  navigator.getUserMedia  = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;

  var recorder;
  var audio = document.querySelector('audio');

  function startRecording() {
	if (navigator.getUserMedia) {
	  navigator.webkitGetUserMedia({audio: true}, onSuccess, onFail);
	} else {
	  console.log('navigator.getUserMedia not present');
	}
  }

  function stopRecording() {
	recorder.stop();
	recorder.exportWAV(function(s) {
	  audio.src = window.URL.createObjectURL(s);
    stageRecording(s);
	});
}

  function stageRecording(blob) {
    userRecording = blob;
  }

  function sendWaveToPost() {
            var data = new FormData(document.getElementById("audio_form"));
            var id = document.getElementById('identification').innerHTML;
            id = id.replace(/\s/g, '');
            if (userRecording != null) {
              data.append("audio", userRecording, (new Date()).getTime() + ".wav");
          }
            data.append("id", id.toString());
            var str1 = "/submissions/";
            $.ajax({ url: str1.concat(id).concat("?format=json"),
                    type: 'PATCH',
                    beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
                    data: data,
                    processData: false,
                    contentType: false,
                    success: function(response) {
                      alert(response.message);
                      window.location = document.URL.replace('edit', '');
                    }
            });
            
        }


</script>


<div id="content_container">

  <div id="text">


    <h3> Text </h3>
    <p>
      <%= simple_format(@submission.text)%>
    </p>
  

  </div>
  <h4> Enter Username and then record or upload recording </h4>
  <div id="audio_upload_container">
    <form id="audio_form" enctype="multipart/form-data">
      Username: <input type="text" id="userbox" name="user"><br><br>
      File <input type="file" accept=".wav" id="audio_file" name="audio_file">
    </form>
   
    <ol> To Record:
     <li> Click "start recording" (and click "Allow" on your browser if necessary)</li>
     <li> Speak clearly into your machine's microphone</li>
     <li> Click "stop recording and play" to hear your recording</li>
     <li> Click "save recording" if you are satisfied with your recording. Otherwise, click "start recording" to record again </li>
    </ol>



  <audio controls autoplay></audio>
  <div id="button_container">
  <input onclick="startRecording()" type="button" value="start recording" />
  <input onclick="stopRecording()" type="button" value="stop recording and play" />
  </div>


    <input onclick="sendWaveToPost()" type="button" value="Save recording" />
  </div>

</div>

app/views/submissions/index.html.erb
<link rel="stylesheet" type="text/css" src="table_style.css">
<div id="arrow">
  <%= link_to '<- Make New Submission', new_submission_path %>
</div>
<div id="title_container">
  <h1>All Submissions</h1>
</div>
<table>
	<tr>
		<th>Title </th>
    <th>Date/Time Created</th>
    <th>Uploaded By</th>
		<th>Recording </th>
    <th>Date/Time Recorded</th>
    <th>Recorded By</th>
    <th>Delete</th>
	</tr>


	<% @submissions.each do |submission| %>
    
    <tr>      
      <td>
      <%= link_to submission_path(submission) do %>
      <%= submission.title %>
      <% end %>
      </td>
      <td><%= submission.created_at.to_formatted_s %> </td>
      <td><%= submission.textuser %></td>
      <td><% if submission.recording.nil?  %>
          <%= link_to 'Add Recording', edit_submission_path(submission) %>
           <% else %> 
           <%= link_to 'View', submission_path(submission) %>  
            <% end %>  </td>
      <td><% if !submission.recording.nil?  %>
          <%= submission.updated_at.to_formatted_s %>
            <% end %>  </td>
      <td><% if !submission.recording.nil?  %>
          <%= submission.audiouser %>   
            <% end %>  </td>
      <td><%= link_to 'Delete', submission_path(submission),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<p> Note: At this point, recording only functions on Chrome. Also, the recorder is only guaranteed to work if accessed by clicking the "Add Recording" link from this "submissions" page. </p>

app/views/submissions/new.html.erb
<script type="text/javascript" src="reader.js"></script>
<link rel="stylesheet" type="text/css" src="upload.css">
<div id="arrow"><p>&lt;- <%= link_to "Cancel", submissions_path %> </p></div>
<div id="title_container">
  <h1> Create Submission </h1>
</div>


<%= form_for :submission, url: submissions_path do |f| %>
  <% if @submission.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@submission.errors.count, "error") %> prohibited
      this submission from being saved:</h2>
    <ul>
    <% @submission.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<div id="input_container_container">
  <div class="input_container">
 <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  </div>
  <div class="input_container">
  <p>
     <%= f.label "Username" %>
    <%= f.text_field :textuser %>
  </p>
  </div>
</div>
<div id="upload_text">
	<h2> Upload a .txt file or copy and paste</h2>
  <div id="form_container">
      Select a text file: 
      <input type="file" id="fileInput">
  </div>
  <div id="form_container2">
  <p>
    <%= f.label :text %>
    <%= f.text_area :text , id: "populate" %>
  </p>
  </div>
  </div>
  <div id="button_container">
  <p>
    <%= f.submit 'Record Voiceover'%>
    <%= f.submit 'Save Without Recording'%>
  </p>
  </div>

<% end %>

app/views/submissions/show.html.erb
<link rel="stylesheet" type="text/css" src="submission_style.css">
<div id="arrow">
  <%= link_to "<- Back to recordings", submissions_path %>
</div>
<div id="title_container">
    <h1> <%= @submission.title %> </h1>
</div>

<div id="content_div">
    <div class="text_container">
        <h2> Author </h2>
        <%= @submission.textuser %>
    </div>
    <div class="text_container">
        <h2> Text </h2>
        <p><%= simple_format(@submission.text) %></p>
    </div>
    <div class="text_container">
        <h2> Audio File </h2>



<p><% if !@submission.recording.nil?  %>
    Audio recorded by <%= @submission.audiouser %>
    at <%= @submission.updated_at.to_formatted_s %> 
    
    <p>
        <%= link_to "Download Recording", "/submissions/#{@submission.id}/download_audio"  %>
    </p>
    <%end %>
</p>
</div>
<div class="text_container">
    <h2> Timestamp </h2>
    <%= @submission.created_at %>
</div>
</div>

app/views/welcome/index.html.erb
<link rel="stylesheet" type="text/css" src="homepage.css">
<div id="title_container"><h1>Benetech Voice Recorder</h1></div>
<div id="buttons_container">
<%= link_to new_submission_path do %>
<div id="link_button1" class="link_button">Upload
</div>
<% end %>
<%= link_to controller: "submissions" do %>
<div id="link_button2" class="link_button">View All</div>
<% end %>
</div>